export { isEnvironmentCI } from "./is_ci.ts";
export { isEnvironmentDocker, isEnvironmentDockerSync } from "./is_docker.ts";
export { isEnvironmentHeroku } from "./is_heroku.ts";
export { isEnvironmentHyper } from "./is_hyper.ts";
export { isEnvironmentPodman, isEnvironmentPodmanSync } from "./is_podman.ts";
export { isEnvironmentRoot } from "./is_root.ts";
export { isEnvironmentSSH } from "./is_ssh.ts";
export { isEnvironmentTravis } from "./is_travis.ts";
export { isEnvironmentWSL, isEnvironmentWSLSync } from "./is_wsl.ts";
export { getEnvironmentPaths } from "./path.ts";
export { getEnvironmentPathExts } from "./pathext.ts";
export { environmentValueDelimiter } from "./value_delimiter.ts";
